In [ ]:
# this is a shell 
print("hello world")

In [ ]:
!pip3 install numpy

# we are going to learn numpy now

#### this is a new headline

In [3]:
import numpy as np 

In [4]:
# np is the alias of  numpy package

In [5]:
arr= np.array([[1,2,3],
             [4,2,5]])

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim # bumber of dimension 2d array

2

In [9]:
arr.shape # number of rows and column

(2, 3)

In [11]:
arr= np.array([1,2,3])

In [13]:
arr.shape # 3elements

(3,)

In [14]:
arr= np.array([[1,2,3],
             [4,2,5]])

In [17]:
arr.size  # number of elements

6

In [18]:
arr.dtype

dtype('int32')

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
np.arange?

In [31]:
np.arange(0,30,5)

array([ 0,  5, 10, 15, 20, 25])

In [34]:
np.linspace(0,5,10) # 10  values with in the range of 0 to 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [35]:
np.random.random((2,2))

array([[0.34485108, 0.62322831],
       [0.21633965, 0.45223378]])

In [37]:
arr=np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
newarr=arr.reshape(2,2,3)

In [38]:
print(newarr)

[[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [41]:
arr=np.array([[1,2,3,4],
             [5,2,4,2],
             [1,2,0,1]])
newarr=arr.reshape(4,3)

In [42]:
newarr

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

# array indexing in numpy

In [49]:
#               0  1 2 3
arr=np.array([[-1,2,0,4],
             [4,-0.5,6,0],
             [2.6,0,7,8],
             [3,-7,4,2.0]])

In [47]:
#arr[rows,columns]

In [48]:
arr[1:, :3]

array([[ 4. , -0.5,  6. ],
       [ 2.6,  0. ,  7. ],
       [ 3. , -7. ,  4. ]])

In [50]:
arr[1: , :3:2]

array([[4. , 6. ],
       [2.6, 7. ],
       [3. , 4. ]])

In [51]:
arr[1::2 , :3:2]

array([[4., 6.],
       [3., 4.]])

In [53]:
# arr[start:end+1:step , start:end+1:step]

In [60]:
a=np.array([1,2,5,3])

In [61]:
a+1

array([2, 3, 6, 4])

In [62]:
a*3

array([ 3,  6, 15,  9])

In [63]:
# for getting the transpose of the numpy array
# a.T

In [64]:
 # arr.max()-  largest element in whole numpy array     arr.min()-.......

In [66]:
 # arr.max(axis=0)- max in row 0....simly all one

In [67]:
# we can do a+b,a*b,a.dot(b)-dot product

In [68]:
# sorting
#if we wnat to do row wise then---np.sort(a,axis=1)
# if column wise then  ------ np.sort(a,axis=0)

In [69]:
#u can give kind='mergesort'

In [70]:
import numpy as np

# creating array object
arr = np.array([[ 1, 2, 3],
                [ 4, 2, 5]])

# printing type of arr object
print("Array is of type: ", type(arr))

# printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# printing shape of array
print("Shape of array: ", arr.shape)

# printing size (total number of elements) of array
print("Size of array: ", arr.size)

# printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32
